/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ParkingSpace } from "./ParkingSpace";
import { ParkingSpaceCountArgs } from "./ParkingSpaceCountArgs";
import { ParkingSpaceFindManyArgs } from "./ParkingSpaceFindManyArgs";
import { ParkingSpaceFindUniqueArgs } from "./ParkingSpaceFindUniqueArgs";
import { DeleteParkingSpaceArgs } from "./DeleteParkingSpaceArgs";
import { ParkingSpaceService } from "../parkingSpace.service";
@graphql.Resolver(() => ParkingSpace)
export class ParkingSpaceResolverBase {
  constructor(protected readonly service: ParkingSpaceService) {}

  async _parkingSpacesMeta(
    @graphql.Args() args: ParkingSpaceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ParkingSpace])
  async parkingSpaces(
    @graphql.Args() args: ParkingSpaceFindManyArgs
  ): Promise<ParkingSpace[]> {
    return this.service.parkingSpaces(args);
  }

  @graphql.Query(() => ParkingSpace, { nullable: true })
  async parkingSpace(
    @graphql.Args() args: ParkingSpaceFindUniqueArgs
  ): Promise<ParkingSpace | null> {
    const result = await this.service.parkingSpace(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ParkingSpace)
  async deleteParkingSpace(
    @graphql.Args() args: DeleteParkingSpaceArgs
  ): Promise<ParkingSpace | null> {
    try {
      return await this.service.deleteParkingSpace(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
